package db

const (
	/* GetParterConfig query to get all partners and related configurations for a given pub,profile,version
	Data is ordered by partnerId,keyname and entityId so that version level partner params will override the account level partner parasm in the code logic
	*/
	GetParterConfig                   = `SELECT /*+ MAX_EXECUTION_TIME(%d) */ IFNULL(wcm.partner_id, -1) as partnerId, CASE WHEN (wcm.partner_id is NULL) THEN "ALL" ELSE wp.prebid_partner_name END AS prebidPartnerName, CASE WHEN (wcm.partner_id is NULL) THEN "ALL" ELSE wpp.bidder_code END AS bidderCode, CASE WHEN (wcm.partner_id is NULL) THEN 0 ELSE wpp.is_alias END AS isAlias, CASE WHEN (wcm.partner_id is NULL) THEN -1 ELSE entity_type_id END AS entityTypeID, test_config as testConfig, key_name AS keyName, value FROM wrapper_config_map wcm JOIN wrapper_key_master wkm ON wkm.id=wcm.config_id AND entity_type_id = 3 AND entity_id = #VERSION_ID AND wcm.is_active=1 LEFT JOIN wrapper_publisher_partner wpp ON wcm.partner_id=wpp.id LEFT JOIN wrapper_partner wp ON wpp.partner_id = wp.id UNION SELECT distinct(wppvt.partner_id) AS partnerId, "-" AS prebidPartnerName, "-" AS bidderCode, 0 as isAlias, -1 as entityTypeID, 0 as testConfig, 'kgp' AS keyName, key_gen_pattern AS value FROM wrapper_mapping_template JOIN wrapper_profile_partner_version_template wppvt ON version_id = #VERSION_ID AND template_id=id UNION SELECT partner_id as partnerId, "-" AS prebidPartnerName, "-" AS bidderCode, 0 AS isAlias, entity_type_id AS entityTypeID, test_config as testConfig, (SELECT key_name FROM wrapper_key_master WHERE id=config_id) AS keyName, value FROM wrapper_config_map wcm WHERE entity_type_id=1 AND partner_id is NOT NULL AND EXISTS (SELECT partner_id FROM wrapper_config_map WHERE partner_id=wcm.partner_id AND is_active=1 AND entity_type_id = 3 AND entity_id = #VERSION_ID LIMIT 1) ORDER BY partnerId, keyName, entityTypeId`
	DisplayVersionInnerQuery          = "SELECT wv.id as versionId, display_version AS displayVersionId FROM wrapper_version wv JOIN wrapper_profile wp ON profile_id=wp.id WHERE profile_id=? and display_version=? AND pub_id=?"
	LiveVersionInnerQuery             = "SELECT wv.id as versionId, display_version as displayVersionId FROM wrapper_version wv JOIN wrapper_status ws on profile_id=? AND version_id=id and status IN ('LIVE','LIVE_PENDING') JOIN wrapper_profile wp ON profile_id=wp.id AND pub_id=?"
	GetWrapperSlotMappingsQuery       = "SELECT wpsm.partner_id as PartnerId, wpp.partner_id as AdapterId, wpsm.version_id as VersionId, wpsm.slotname as SlotName, wpsm.json_mapping as MappingJson, wpsm.order_id as OrderId FROM wrapper_partner_slot_mapping wpsm join wrapper_version wv on wv.id = wpsm.version_id AND wv.profile_id = #PROFILE_ID AND wv.display_version = #DISPLAY_VERSION and wpsm.partner_id in (#PARTNER_IDS) and wpsm.is_active = 1 join wrapper_publisher_partner wpp on wpp.id = wpsm.partner_id JOIN wrapper_profile wpr ON wpr.id = wv.profile_id order by wpsm.order_id"
	GetWrapperLiveVersionSlotMappings = "SELECT wpsm.partner_id as PartnerId, wpp.partner_id as AdapterId, wpsm.version_id as VersionId, wpsm.slotname as SlotName, wpsm.json_mapping as MappingJson, wpsm.order_id as OrderId FROM wrapper_partner_slot_mapping wpsm JOIN wrapper_version wv ON wv.id = wpsm.version_id AND wv.profile_id = #PROFILE_ID AND wpsm.partner_id IN ( #PARTNER_IDS ) AND wpsm.is_active = 1 join wrapper_publisher_partner wpp on wpp.id = wpsm.partner_id JOIN wrapper_status ws ON wv.id = ws.version_id and ws.status IN ( 'LIVE', 'LIVE_PENDING' ) JOIN wrapper_profile wpr ON wpr.id = wv.profile_id order by wpsm.order_id"
	GetPMSlotToMappings               = "SELECT CONCAT(slot_name,'@',pm_size) AS slot_name, pm_size, pm_site_id, ad_tag_id, ga_id, floor FROM giym.publisher_slot_to_tag_mapping WHERE pub_id = ? AND profile_id = 0 AND version_id = 0 AND status IN ('LIVE', 'NEW') ORDER BY BINARY slot_name LIMIT ?"
	GetAdunitConfigQuery              = "SELECT cf.config_json AS adunitConfig FROM wrapper_media_config cf JOIN wrapper_version wv ON cf.version_id = wv.id AND cf.is_active=1 AND wv.profile_id = #PROFILE_ID AND wv.display_version = #DISPLAY_VERSION"
	GetAdunitConfigForLiveVersion     = "SELECT cf.config_json AS adunitConfig FROM wrapper_media_config cf JOIN wrapper_version wv ON cf.version_id = wv.id AND cf.is_active=1 AND wv.profile_id = #PROFILE_ID JOIN wrapper_status ws ON wv.id = ws.version_id and ws.status IN ('LIVE','LIVE_PENDING')"
	GetSlotNameHash                   = `SELECT name, hash FROM wrapper_publisher_slot WHERE pub_id = #PUB_ID`
	GetPublisherVASTTagsQuery         = `SELECT wvt.id AS id, wvt.partner_id AS partnerId, wvt.url AS url, wvt.duration AS duration, IFNULL(wvt.price,0.0) AS price FROM wrapper_publisher_partner_vast_tag wvt WHERE wvt.pub_id = #PUB_ID AND wvt.deleted = 0 AND wvt.status="live" ORDER BY wvt.partner_id`

	PartnerIdKey      = "#PARTNER_IDS"
	ProfileIdKey      = "#PROFILE_ID"
	PubIdKey          = "#PUB_ID"
	DisplayVersionKey = "#DISPLAY_VERSION"
	VersionIdKey      = "#VERSION_ID"
)
