package metrics

// MetricsEngine is a generic interface to record PBS metrics into the desired backend
type MetricsEngine interface {
	RecordOpenWrapServerPanicStats()
	RecordPublisherPartnerStats(publisher, partner string)
	RecordPublisherPartnerImpStats(publisher, partner string, impCount int)
	RecordPublisherPartnerNoCookieStats(publisher, partner string)
	RecordPartnerTimeoutErrorStats(publisher, partner string)
	RecordNobiderStatusErrorStats(publisher, partner string)
	RecordNobidErrorStats(publisher, partner string)
	RecordUnkownPrebidErrorStats(publisher, partner string)
	RecordSlotNotMappedErrorStats(publisher, partner string)
	RecordMisConfigurationErrorStats(publisher, partner string)
	RecordPublisherProfileRequests(publisher, profileID string)
	RecordPublisherInvalidProfileImpressions(publisher, profileID string, impCount int)
	RecordPublisherNoConsentRequests(publisher string)
	RecordPublisherNoConsentImpressions(publisher string, impCount int)
	RecordPublisherRequestStats(publisher string)
	RecordNobidErrPrebidServerRequests(publisher string)
	RecordNobidErrPrebidServerResponse(publisher string)
	RecordInvalidCreativeStats(publisher, partner string)
	RecordPlatformPublisherPartnerReqStats(platform, publisher, partner string)
	RecordPlatformPublisherPartnerResponseStats(platform, publisher, partner string)
	RecordPublisherResponseEncodingErrorStats(publisher string)
	RecordPartnerResponseTimeStats(publisher, partner string, responseTime int)
	RecordPublisherResponseTimeStats(publisher string, responseTime int)
	RecordPublisherWrapperLoggerFailure(publisher, profileID, versionID string)
	RecordCacheErrorRequests(endpoint string, publisher string, profileID string)
	RecordPublisherInvalidProfileRequests(endpoint, publisher, profileID string)
	RecordBadRequests(endpoint string, errorCode int)
	RecordPrebidTimeoutRequests(publisher, profileID string)
	RecordSSTimeoutRequests(publisher, profileID string)
	RecordUidsCookieNotPresentErrorStats(publisher, profileID string)
	RecordVideoInstlImpsStats(publisher, profileID string)
	RecordImpDisabledViaConfigStats(impType, publisher, profileID string)
	RecordPreProcessingTimeStats(publisher string, processingTime int)
	RecordStatsKeyCTVPrebidFailedImpression(errorcode int, publisher string, profile string)
	RecordCTVRequests(endpoint string, platform string)
	RecordPublisherRequests(endpoint string, publisher string, platform string)
	RecordCTVHTTPMethodRequests(endpoint string, publisher string, method string)
	RecordCTVInvalidReasonCount(errorCode int, publisher string)
	RecordCTVIncompleteAdPodsCount(impCount int, reason string, publisher string)
	RecordCTVReqImpsWithDbConfigCount(publisher string)
	RecordCTVReqImpsWithReqConfigCount(publisher string)
	RecordAdPodGeneratedImpressionsCount(impCount int, publisher string)
	RecordRequestAdPodGeneratedImpressionsCount(impCount int, publisher string)
	RecordAdPodSecondsMissedCount(seconds int, publisher string)
	RecordReqImpsWithAppContentCount(publisher string)
	RecordReqImpsWithSiteContentCount(publisher string)
	RecordAdPodImpressionYield(maxDuration int, minDuration int, publisher string)
	RecordCTVReqCountWithAdPod(publisherID, profileID string)
	RecordCTVKeyBidDuration(duration int, publisherID, profileID string)
	RecordPBSAuctionRequestsStats()
	RecordInjectTrackerErrorCount(adformat, publisher, partner string)
	RecordBidResponseByDealCountInPBS(publisher, profile, aliasBidder, dealId string)
	RecordBidResponseByDealCountInHB(publisher, profile, aliasBidder, dealId string)
	RecordPartnerTimeoutInPBS(publisher, profile, aliasBidder string)
	RecordVideoImpDisabledViaConnTypeStats(publisher, profileID string)
}
