// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pm-nilesh-chate/prebid-server/modules/pubmatic/openwrap/database (interfaces: Database)

// Package mock_database is a generated GoMock package.
package mock_database

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/prebid/prebid-server/modules/pubmatic/openwrap/models"
	adunitconfig "github.com/prebid/prebid-server/modules/pubmatic/openwrap/models/adunitconfig"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// GetActivePartnerConfigurations mocks base method.
func (m *MockDatabase) GetActivePartnerConfigurations(arg0, arg1, arg2 int) (map[int]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePartnerConfigurations", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[int]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePartnerConfigurations indicates an expected call of GetActivePartnerConfigurations.
func (mr *MockDatabaseMockRecorder) GetActivePartnerConfigurations(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePartnerConfigurations", reflect.TypeOf((*MockDatabase)(nil).GetActivePartnerConfigurations), arg0, arg1, arg2)
}

// GetAdunitConfig mocks base method.
func (m *MockDatabase) GetAdunitConfig(arg0, arg1 int) (*adunitconfig.AdUnitConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdunitConfig", arg0, arg1)
	ret0, _ := ret[0].(*adunitconfig.AdUnitConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdunitConfig indicates an expected call of GetAdunitConfig.
func (mr *MockDatabaseMockRecorder) GetAdunitConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdunitConfig", reflect.TypeOf((*MockDatabase)(nil).GetAdunitConfig), arg0, arg1)
}

// GetMappings mocks base method.
func (m *MockDatabase) GetMappings(arg0 string, arg1 map[string]models.SlotMapping) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappings", arg0, arg1)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappings indicates an expected call of GetMappings.
func (mr *MockDatabaseMockRecorder) GetMappings(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappings", reflect.TypeOf((*MockDatabase)(nil).GetMappings), arg0, arg1)
}

// GetPublisherSlotNameHash mocks base method.
func (m *MockDatabase) GetPublisherSlotNameHash(arg0 int) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublisherSlotNameHash", arg0)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetPublisherSlotNameHash indicates an expected call of GetPublisherSlotNameHash.
func (mr *MockDatabaseMockRecorder) GetPublisherSlotNameHash(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublisherSlotNameHash", reflect.TypeOf((*MockDatabase)(nil).GetPublisherSlotNameHash), arg0)
}

// GetPublisherVASTTags mocks base method.
func (m *MockDatabase) GetPublisherVASTTags(arg0 int) (map[int]*models.VASTTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublisherVASTTags", arg0)
	ret0, _ := ret[0].(map[int]*models.VASTTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublisherVASTTags indicates an expected call of GetPublisherVASTTags.
func (mr *MockDatabaseMockRecorder) GetPublisherVASTTags(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublisherVASTTags", reflect.TypeOf((*MockDatabase)(nil).GetPublisherVASTTags), arg0)
}

// GetPubmaticSlotMappings mocks base method.
func (m *MockDatabase) GetPubmaticSlotMappings(arg0 int) map[string]models.SlotMapping {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPubmaticSlotMappings", arg0)
	ret0, _ := ret[0].(map[string]models.SlotMapping)
	return ret0
}

// GetPubmaticSlotMappings indicates an expected call of GetPubmaticSlotMappings.
func (mr *MockDatabaseMockRecorder) GetPubmaticSlotMappings(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPubmaticSlotMappings", reflect.TypeOf((*MockDatabase)(nil).GetPubmaticSlotMappings), arg0)
}

// GetWrapperSlotMappings mocks base method.
func (m *MockDatabase) GetWrapperSlotMappings(arg0 map[int]map[string]string, arg1, arg2 int) map[int][]models.SlotMapping {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWrapperSlotMappings", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[int][]models.SlotMapping)
	return ret0
}

// GetWrapperSlotMappings indicates an expected call of GetWrapperSlotMappings.
func (mr *MockDatabaseMockRecorder) GetWrapperSlotMappings(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWrapperSlotMappings", reflect.TypeOf((*MockDatabase)(nil).GetWrapperSlotMappings), arg0, arg1, arg2)
}
